name: Deploy to Google App Engine

on:
  push:
    branches: [ main ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install backend dependencies
      run: |
        cd fruit-veggie-api
        npm ci
        
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure App Engine deployment
      run: gcloud config set app/use_deprecated_preparation True
        
    - name: Deploy backend to App Engine
      run: |
        cd fruit-veggie-api
        gcloud app deploy --quiet

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install frontend dependencies
      run: |
        cd fruit-veggie-app
        npm ci
        
    - name: Build frontend
      run: |
        cd fruit-veggie-app
        npm run build
        
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
        
    - name: Deploy frontend to App Engine
      run: |
        cd fruit-veggie-app
        gcloud app deploy --quiet